apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  labels:
    run: mynginx-rs
  name: mynginx-rs
spec:
  replicas: 3
  selector:
    matchLabels:
      app_runtime_stage: staging
  template:
    metadata:
      labels:
        app_runtime_stage: staging
    spec:
      containers:
      - image: nginx
        name: nginx-app
